---
title: "HW2 - Birds Analysis"
author: "John C. Manyiel"
date: "9/15/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---



```{r setup,include=FALSE} 
knitr::opts_chunk$set(
    message=FALSE, 
    error=FALSE, 
    warning=FALSE, 
    comment=NA,
    echo=TRUE,
    collapse=TRUE, 
    out.width = "100%"
    )
```


Load packages

```{r }
library(rprojroot)
#root<-has_file(".ROS-Examples-root")$make_fix_file()
library(rstanarm)
library(arm)
library(ggplot2)
library(bayesplot)
library(tidyverse)
library(stringr)
library(pdftools)
library(stringr)
library(xlsx)
library(dbplyr)
theme_set(bayesplot::theme_default(base_family = "sans"))
```


Load Data


```{r}



df <- read.csv("Z:/Development/DatumAnalyticConsulting/DACSS601Fall21/_data/birds.csv")

head(df)

```

Learn & Explore the data set


```{r}

df_sum <-  summary(df)

df_sum



```
```{r}

dfdetails<-  str(df)

dfdetails
```

Select random from Bird Data


```{r}


df_smaple <-  sample_frac(df, 0.1)
head(df_smaple[1:5])


```



Data Transformation & Wrangling: discorvered that we would need to 
transform the data before. 

```{r}
df1 <-  as_tibble(df)  %>%   
              group_by(Area) %>% 
  
                 filter( 
                        Area =="Northern America" | 
                        Area == "United States of America" |
                        Area == "Canada"| 
                        Area == "Mexico"|
                        Area == "American Samoa" |
                        Area  == "United States Virgin Islands" 
                        ) %>% summarise(sum(Value))
arrange(df1,desc(`sum(Value)`))

```


Notice that North America value is combination of all the states. 
I would need to transform the data further. 



